/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSolicitarRouteImport } from './routes/_authenticated/app.solicitar'
import { Route as AuthenticatedAppSolicitacoesRouteImport } from './routes/_authenticated/app.solicitacoes'
import { Route as AuthenticatedAppPortfolioRouteImport } from './routes/_authenticated/app.portfolio'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppPainelRouteImport } from './routes/_authenticated/app.painel'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppBuscarRouteImport } from './routes/_authenticated/app.buscar'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppPrestadorIdRouteImport } from './routes/_authenticated/app.prestador.$id'
import { Route as AuthenticatedAppChatIdRouteImport } from './routes/_authenticated/app.chat.$id'
import { Route as AuthenticatedAppCategoriaIdRouteImport } from './routes/_authenticated/app.categoria.$id'
import { Route as AuthenticatedAppAvaliarContratoIdRouteImport } from './routes/_authenticated/app.avaliar.$contratoId'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat.'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSolicitarRoute =
  AuthenticatedAppSolicitarRouteImport.update({
    id: '/solicitar',
    path: '/solicitar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSolicitacoesRoute =
  AuthenticatedAppSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPortfolioRoute =
  AuthenticatedAppPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPainelRoute = AuthenticatedAppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBuscarRoute = AuthenticatedAppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPrestadorIdRoute =
  AuthenticatedAppPrestadorIdRouteImport.update({
    id: '/prestador/$id',
    path: '/prestador/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatIdRoute = AuthenticatedAppChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppChatRoute,
} as any)
const AuthenticatedAppCategoriaIdRoute =
  AuthenticatedAppCategoriaIdRouteImport.update({
    id: '/categoria/$id',
    path: '/categoria/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAvaliarContratoIdRoute =
  AuthenticatedAppAvaliarContratoIdRouteImport.update({
    id: '/avaliar/$contratoId',
    path: '/avaliar/$contratoId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/painel': typeof AuthenticatedAppPainelRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/solicitacoes': typeof AuthenticatedAppSolicitacoesRoute
  '/app/solicitar': typeof AuthenticatedAppSolicitarRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/chat/': typeof AuthenticatedAppChatRoute
  '/app/avaliar/$contratoId': typeof AuthenticatedAppAvaliarContratoIdRoute
  '/app/categoria/$id': typeof AuthenticatedAppCategoriaIdRoute
  '/app/chat/$id': typeof AuthenticatedAppChatIdRoute
  '/app/prestador/$id': typeof AuthenticatedAppPrestadorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/painel': typeof AuthenticatedAppPainelRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/solicitacoes': typeof AuthenticatedAppSolicitacoesRoute
  '/app/solicitar': typeof AuthenticatedAppSolicitarRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/avaliar/$contratoId': typeof AuthenticatedAppAvaliarContratoIdRoute
  '/app/categoria/$id': typeof AuthenticatedAppCategoriaIdRoute
  '/app/chat/$id': typeof AuthenticatedAppChatIdRoute
  '/app/prestador/$id': typeof AuthenticatedAppPrestadorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/painel': typeof AuthenticatedAppPainelRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/_authenticated/app/solicitacoes': typeof AuthenticatedAppSolicitacoesRoute
  '/_authenticated/app/solicitar': typeof AuthenticatedAppSolicitarRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/avaliar/$contratoId': typeof AuthenticatedAppAvaliarContratoIdRoute
  '/_authenticated/app/categoria/$id': typeof AuthenticatedAppCategoriaIdRoute
  '/_authenticated/app/chat/$id': typeof AuthenticatedAppChatIdRoute
  '/_authenticated/app/prestador/$id': typeof AuthenticatedAppPrestadorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/agenda'
    | '/app/buscar'
    | '/app/chat'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/app/painel'
    | '/app/perfil'
    | '/app/portfolio'
    | '/app/solicitacoes'
    | '/app/solicitar'
    | '/app/'
    | '/app/chat/'
    | '/app/avaliar/$contratoId'
    | '/app/categoria/$id'
    | '/app/chat/$id'
    | '/app/prestador/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/agenda'
    | '/app/buscar'
    | '/app/financeiro'
    | '/app/onboarding'
    | '/app/painel'
    | '/app/perfil'
    | '/app/portfolio'
    | '/app/solicitacoes'
    | '/app/solicitar'
    | '/app'
    | '/app/chat'
    | '/app/avaliar/$contratoId'
    | '/app/categoria/$id'
    | '/app/chat/$id'
    | '/app/prestador/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/buscar'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/painel'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/portfolio'
    | '/_authenticated/app/solicitacoes'
    | '/_authenticated/app/solicitar'
    | '/_authenticated/app/'
    | '/_authenticated/app/chat/'
    | '/_authenticated/app/avaliar/$contratoId'
    | '/_authenticated/app/categoria/$id'
    | '/_authenticated/app/chat/$id'
    | '/_authenticated/app/prestador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/solicitar': {
      id: '/_authenticated/app/solicitar'
      path: '/solicitar'
      fullPath: '/app/solicitar'
      preLoaderRoute: typeof AuthenticatedAppSolicitarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/solicitacoes': {
      id: '/_authenticated/app/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/app/solicitacoes'
      preLoaderRoute: typeof AuthenticatedAppSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portfolio': {
      id: '/_authenticated/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AuthenticatedAppPortfolioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/painel': {
      id: '/_authenticated/app/painel'
      path: '/painel'
      fullPath: '/app/painel'
      preLoaderRoute: typeof AuthenticatedAppPainelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/buscar': {
      id: '/_authenticated/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AuthenticatedAppBuscarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prestador/$id': {
      id: '/_authenticated/app/prestador/$id'
      path: '/prestador/$id'
      fullPath: '/app/prestador/$id'
      preLoaderRoute: typeof AuthenticatedAppPrestadorIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/$id': {
      id: '/_authenticated/app/chat/$id'
      path: '/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AuthenticatedAppChatIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/categoria/$id': {
      id: '/_authenticated/app/categoria/$id'
      path: '/categoria/$id'
      fullPath: '/app/categoria/$id'
      preLoaderRoute: typeof AuthenticatedAppCategoriaIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/avaliar/$contratoId': {
      id: '/_authenticated/app/avaliar/$contratoId'
      path: '/avaliar/$contratoId'
      fullPath: '/app/avaliar/$contratoId'
      preLoaderRoute: typeof AuthenticatedAppAvaliarContratoIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppChatIdRoute: typeof AuthenticatedAppChatIdRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppChatIdRoute: AuthenticatedAppChatIdRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBuscarRoute: typeof AuthenticatedAppBuscarRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppPainelRoute: typeof AuthenticatedAppPainelRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppPortfolioRoute: typeof AuthenticatedAppPortfolioRoute
  AuthenticatedAppSolicitacoesRoute: typeof AuthenticatedAppSolicitacoesRoute
  AuthenticatedAppSolicitarRoute: typeof AuthenticatedAppSolicitarRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAvaliarContratoIdRoute: typeof AuthenticatedAppAvaliarContratoIdRoute
  AuthenticatedAppCategoriaIdRoute: typeof AuthenticatedAppCategoriaIdRoute
  AuthenticatedAppPrestadorIdRoute: typeof AuthenticatedAppPrestadorIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBuscarRoute: AuthenticatedAppBuscarRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppPainelRoute: AuthenticatedAppPainelRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppPortfolioRoute: AuthenticatedAppPortfolioRoute,
  AuthenticatedAppSolicitacoesRoute: AuthenticatedAppSolicitacoesRoute,
  AuthenticatedAppSolicitarRoute: AuthenticatedAppSolicitarRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAvaliarContratoIdRoute:
    AuthenticatedAppAvaliarContratoIdRoute,
  AuthenticatedAppCategoriaIdRoute: AuthenticatedAppCategoriaIdRoute,
  AuthenticatedAppPrestadorIdRoute: AuthenticatedAppPrestadorIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
